### ISSUE TITLE
ReflexState natspec

### ISSUE THREAD

**Issue by alcueca** [chromaxyz/reflex#125]
Add a description for ReflexState (or ReflexStorage):

My own notes:
All state variables for Reflex apps are in storage slots that won’t be used by solidity. That means that the modules can be coded in solidity and won’t collide with the reentrancy lock, reflex owner, reflex pending owner, module mapping, endpoint mapping or module to endpoint mapping.
By loading the ReflexStorage struct, all these are loaded into memory (6 words).

**Comment by zerosnacks** [comment]
> My own notes: All state variables for Reflex apps are in storage slots that won’t be used by solidity. That means that the modules can be coded in solidity and won’t collide with the reentrancy lock, reflex owner, reflex pending owner, module mapping, endpoint mapping or module to endpoint mapping. By loading the ReflexStorage struct, all these are loaded into memory (6 words).

It is not recommended modules themselves implement storage using the usual storage layout (0 => 1 => 2, etc..) because storage locations defined in modules will clash with each other.

Consider module A:

`uint256 foo = 128`

Consider module B:

`uint256 bar = 256`

These will both occupy storage slot 0 and clash.

See: 
- https://github.com/chromaxyz/reflex/blob/development/docs/IMPLEMENTERS.md#storage

It is recommended that if modules do require their own storage variables they use unstructured storage, preferably as formalized in [EIP-7201](https://github.com/chromaxyz/reflex/pull/123) with which Reflex is compatible.

Reflex defining storage in this way allows itself it to be upgraded to new versions.

OpenZeppelin previously definined storage `__GAP`'s and manual management of the slots to do something similar but in V5 they switched to EIP-7201.


> By loading the ReflexStorage struct, all these are loaded into memory (6 words).

It is usually not recommended to not load the entire struct but rather access individual elements (`_REFLEX_STORAGE().foo`), this (to my knowledge) would only load a single word.

**Comment by alcueca** [comment]
You are right, this is also made clear in the documentation, which I unfortunately didn't find until today.
